<a href="https://colab.research.google.com/github/yanil-03/Deep-Learning/blob/main/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Text representation

In [3]:
# 1. bag of words
# we use countvectorization

In [4]:
import numpy as np
import pandas as pd

In [7]:
df = pd.DataFrame({'text':['people watch cricket','player was player',
                           'people write comment',
                           'cricket play comment'],'output':[1,1,0,0]})

In [8]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [10]:
bow = cv.fit_transform(df['text'])


In [14]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]


In [16]:
cv.transform(['cricket watch and write comment of cricket comment']).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

In [17]:
# 2. N-grams
v = CountVectorizer(ngram_range=(1,2))

In [18]:
bow = v.fit_transform(df['text'])

In [19]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [20]:
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}


In [21]:
# TF(term frequency)
# 2. IDF(inverse document frequency)

In [22]:
# from ast import MatchSingleton
# TF(t,d) = (number of occurance of term t in document d)/(total number of terms in document d)
# example=>
# d1 = people watch cricket

# tf(people,d1) = 1/3

# d2 = match was match
# tf(match,d2) = 2/3

In [24]:
# from logging import log
# IDF(t) = Loge(Total number of documents)/(number of documents with term t in it)

# here corpus means number of sentences

# Example ==>
# d1 = people watch cricket
# d2 = cricket was cricket
# d3 = people play comment
# d4 = cricket write comment

# idf(cricket) = log(4/4)
# idf(people) = log(4/2)

In [25]:
# we can use this by apply feature_extraction method in sklearn

In [26]:
df

text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [28]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']


In [29]:
df = pd.DataFrame({'text':['I love python','python is good',
                           'python is useful'],'output':[1,1,0]})

In [30]:
df

text  output
0     I love python       1
1    python is good       1
2  python is useful       0

In [31]:
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.861037  , 0.50854232, 0.        ],
       [0.72033345, 0.54783215, 0.        , 0.42544054, 0.        ],
       [0.        , 0.54783215, 0.        , 0.42544054, 0.72033345]])

In [32]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.69314718 1.28768207 1.69314718 1.         1.69314718]
['good' 'is' 'love' 'python' 'useful']
